language: python
python:
    - 3.5
    - 3.6
    - 3.7
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
install:
    - pip install -r requirements.txt
env:
    - AWS_DEFAULT_REGION=eu-west-1
# command to run tests
#python -m unittest tests.test_user.py
script: python -m unittest discover
after_success:
  - codecov # submit coverage
